cookies = {"sessionid": "knfwxqms689lv6k8zvxu0gs86bqj2m43"}
back_domain = 'http://backend.pre.igengmei.com'
hera_domain = 'http://hera.s.igengmei.com'
back_end_domain = "http://backend.paas.env"




data = {'platform': 'iPhone', 'os_version': '12.1', 'version': '7.7.40',
        'model': 'iPhone7Plus', 'release': '0', 'idfa': 'A543D573-567D-4852-B342-885DDE460FAE',
        'idfv': '42E06850-2716-49A6-835F-72BBC0E66563', 'device_id': 'A543D573-567D-4852-B342-885DDE460FA6',
        'channel': 'AppStore', 'app_name': 'gengmeiios', 'current_city_id': 'beijing', 'lat': '40.00199243109117',
        'lng': '116.4868137760034', 'is_WiFi': '1'}

seconddata = (('count', '10'), ('start_num', '0'))

myurl = {'/api/answer/vote': '/api/answer/vote',
         '/api/answer/cancel_vote': '/api/answer/cancel_vote',
         '/api/answer/received': '/api/answer/received',
         '/api/consult/free_custom_made': '/api/consult/free_custom_made',
         '/api/consult/free_custom_select_tags': '/api/consult/free_custom_select_tags',
         '/api/conversation/delta_message_detail/': '/api/conversation/delta_message_detail/',
         '/api/conversation/detail/': '/api/conversation/detail/',
         '/api/coupon/claim': '/api/coupon/claim',
         '/api/coupon/list/my': '/api/coupon/list/my',
         '/api/coupon/list/available': '/api/coupon/list/available',
         '/api/customer_srv/init_status': '/api/customer_srv/init_status',
         '/api/customer_srv/is_direct_talk': '/api/customer_srv/is_direct_talk',
         '/api/customer_srv/send_message': '/api/customer_srv/send_message',
         '/api/diary': '/api/diary',
         '/api/diary/additional_info/v2': '/api/diary/additional_info/v2',
         '/api/diary/cancel_vote': '/api/diary/cancel_vote',
         '/api/diary/vote': '/api/diary/vote',
         '/api/diary/create/v2': '/api/diary/create/v2',
         '/api/diary/create_reply': '/api/diary/create_reply',
         '/api/diary/favor/101': '/api/diary/favor/101',
         '/api/diary/image/getall': '/api/diary/image/getall',
         '/api/diary/image/getall/v2': '/api/diary/image/getall/v2',
         '/api/diary/pre_create_topic/v2': '/api/diary/pre_create_topic/v2',
         '/api/diary/recent': '/api/diary/recent',
         '/api/search/v2/diary': '/api/search/v2/diary',
         '/api/maidan/cancel': '/api/maidan/cancel',
         '/api/maidan/create': '/api/maidan/create',
         '/api/maidan/detail': '/api/maidan/detail',
         '/api/maidan/list': '/api/maidan/list',
         '/api/maidan/pay': '/api/maidan/pay',
         '/api/search/keywords': '/api/search/keywords',
         '/api/maidan/preview': '/api/maidan/preview',
         '/api/maidan/tags': '/api/maidan/tags',
         '/api/msg/reply_msg': '/api/msg/reply_msg',
         '/api/my_conversation': '/api/my_conversation',
         '/api/notification': '/api/notification',
         '/api/notification/index/v1': '/api/notification/index/v1',
         '/api/notification/v1': '/api/notification/v1',
         '/api/orders/my/v2': '/api/orders/my/v2',
         '/api/personal/recommends': '/api/personal/recommends',
         '/api/question/create_answer': '/api/question/create_answer',
         '/api/question/create_question': '/api/question/create_question',
         '/api/question/index': '/api/question/index',
         '/api/question/index/v2': '/api/question/index/v2',
         '/api/question/reply_answer': '/api/question/reply_answer',
         '/api/report/info': '/api/report/info',
         '/api/report/upload': '/api/report/upload',
         '/api/reservation/cancel': '/api/reservation/cancel',
         '/api/reservation/create': '/api/reservation/create',
         '/api/reservation/detail': '/api/reservation/detail',
         '/api/reservation/list': '/api/reservation/list',
         '/api/reservation/mine': '/api/reservation/mine',
         '/api/sensitivity/check': '/api/sensitivity/check',
         '/api/service/comment/create': '/api/service/comment/create',
         '/api/service/comment/detail': '/api/service/comment/detail',
         '/api/service/comment/info': '/api/service/comment/info',
         '/api/service/detail/v1': '/api/service/detail/v1',
         '/api/service/favor/': '/api/service/favor/',
         '/api/service/home/v3': '/api/service/home/v3',
         '/api/service/listing_notify': '/api/service/listing_notify',
         '/api/service/reserve/': '/api/service/reserve/',
         '/api/services/v1': '/api/services/v1',
         '/api/settlement/pay': '/api/settlement/pay',
         '/api/settlement/preview/v1': '/api/settlement/preview/v1',
         '/api/shopcart/add/v1': '/api/shopcart/add/v1',
         '/api/shopcart/delete': '/api/shopcart/delete',
         '/api/shopcart/list/v2': '/api/shopcart/list/v2',
         '/api/shopcart/set_number': '/api/shopcart/set_number',
         '/api/tag/list': '/api/tag/list',
         '/api/tool/qr_legal_url': '/api/tool/qr_legal_url',
         '/api/user/answer': '/api/user/answer',
         '/api/user/check_in': '/api/user/check_in',
         '/api/user/favors/diaries': '/api/user/favors/diaries',
         '/api/user/favors/services': '/api/user/favors/services',
         '/api/user/favors/topics': '/api/user/favors/topics',
         '/api/user/follow/add': '/api/user/follow/add',
         '/api/user/follow/del': '/api/user/follow/del',
         '/api/user/following_or_fans': '/api/user/following_or_fans',
         '/api/user/info/': '/api/user/info/',
         '/api/user/my_answer': '/api/user/my_answer',
         '/api/user/my_diary/v2': '/api/user/my_diary/v2',
         '/api/user/my_question': '/api/user/my_question',
         '/api/user/my_topic': '/api/user/my_topic',
         '/api/user/personal_center': '/api/user/personal_center',
         '/api/verification_code': '/api/verification_code',
         '/api/votes/received': '/api/votes/received',
         '/api/zone/detail/v2': '/api/zone/detail/v2',
         '/api/zone/detail/v3': '/api/zone/detail/v3',
         '/api/zone/follow': '/api/zone/follow',
         '/api/zone/my': '/api/zone/my',
         '/api/diary/update/{}': '/api/diary/update/{}',
         '/api/order/{}': '/api/order/{}',
         '/api/order/{}/is_used': '/api/order/{}/is_used',
         '/api/order/refund/{}/': '/api/order/refund/{}/',
         '/api/index/v6': '/api/index/v6',
         '/api/topic/reply/create/{}/': '/api/topic/reply/create/{}/',
         '/api/user/problem_favor/{}/': '/api/user/problem_favor/{}/',
         '/hybrid/question/answer_list/_data': '/hybrid/question/answer_list/_data',
         '/hybrid/topic/{}/': '/hybrid/topic/{}/',
         '/hybrid/topic_reply/{}/': '/hybrid/topic_reply/{}/',
         '/hybrid/wiki': '/hybrid/wiki',
         '/hybrid/organizations/doctors/{}/_data': '/hybrid/organizations/doctors/{}/_data',
         '/api/order/list_for_diary_create': '/api/order/list_for_diary_create',
         '/api/report/reason': '/api/report/reason',
         '/api/app/config_v2': '/api/app/config_v2',
         '/api/get_badge/': '/api/get_badge/',
         '/api/index/float_activity': '/api/index/float_activity',
         '/api/search/default/keywords': '/api/search/default/keywords',
         '/api/user/portrait/update': '/api/user/portrait/update',
         '/api/city/': '/api/city/',
         '/api/user/city/': '/api/user/city/',
         '/api/phone_area_code': '/api/phone_area_code',
         '/api/user/phone/': '/api/user/phone/',
         '/api/user/change_pwd': '/api/user/change_pwd',
         '/api/user/check_pwd': '/api/user/check_pwd',
         '/hybrid/csc/group_qa': '/hybrid/csc/group_qa',
         '/api/doctor_apply/': '/api/doctor_apply/',
         '/hybrid/diary_my/_data': '/hybrid/diary_my/_data',
         '/hybrid/user/add_follow/_data': '/hybrid/user/add_follow/_data',
         '/hybrid/user/del_follow/_data': '/hybrid/user/del_follow/_data',
         '/hybrid/user_following_items/_data': '/hybrid/user_following_items/_data',
         '/hybrid/tag/unfollow/_data': '/hybrid/tag/unfollow/_data',
         '/hybrid/tag/follow/_data': '/hybrid/tag/follow/_data',
         '/api/accounts/stat/': '/api/accounts/stat/',
         '/hybrid/user_qa/_data': '/hybrid/user_qa/_data',
         '/hybrid/answer_detail/_data': '/hybrid/answer_detail/_data',
         '/hybrid/answer_comments_list/_data': '/hybrid/answer_comments_list/_data'
         }

thirddata = {'/api/conversation/detail/': {'last_msg_id': '0',
                                           'offset_msg_id': '0',
                                           'referrer': 'csc_group',
                                           'referrer_id': ''},
             '/api/coupon/list/available': {'coupon_type': '2',
                                             'valid_only': 'true'
                                             },
             '/api/coupon/list/my': {'tab_id': '0'},
             '/api/customer_srv/send_message': {'content': '中国'},
             '/api/diary': {'search_tab': '4', 'area_id': '',
                            'doctor_id': '',
                            'filter_name': 'doctor_diary_filter',
                            'order_by': '0',
                            'service_id': '',
                            'start_num': '0',
                            'tag_id': '',
                            'user_id': ''
                            },
             '/api/diary/additional_info/v2': {'doctor_id': '',
                                               'doctor_name': '',
                                               'hospital_id': '01e1c30183544dbc9a0c2c6b9d67fb84',
                                               'hospital_name': '北京纹玺妊娠纹修复中心',
                                               'only_update_order_info': '0',
                                               'operation_timestamp': '1541635200',
                                               'post_cover': 'http://pic.igengmei.com/2018/11/15/1604/d10474aff36f-thumb',
                                               'pre_cover': '',
                                               'tag_ids': '[64,1,15]',
                                               'title': '日记本标题_双眼皮修复'
                                               },
             '/api/diary/cancel_vote': {'area_id': '',
                                        'input_type': '1',
                                        'order_by': '',
                                        'start_num': '',
                                        'tag_id': '',
                                        'q': '吸脂'},
             '/api/diary/create/v2': {'diary_title': '新建日记本_我是赚取美分的'},
             '/api/diary/create_reply': {'diary_id': '101',
                                         'reply_id': '102'},
             '/api/diary/image/getall/v2': {'count': '20',
                                            'start_num': '0',
                                            'type': '0'},
             '/api/diary/image/getall': {'type': '0',
                                         'start_num': '0',
                                         'count': '0'},
             '/api/diary/pre_create_topic/v2': {'diary_id': ''},
             '/api/diary/vote': {'area_id': '',
                                 'input_type': '1',
                                 'order_by': '',
                                 'start_num': '',
                                 'tag_id': '',
                                 'q': '吸脂'},
             '/api/maidan/create': {'payment': '1',
                                    'tag_ids': '[0]'},
             '/api/personal/recommends': {'area_id': '',
                                          'filter_name': '',
                                          'from': 'diary_list',
                                          'order_by': '0',
                                          'tag_id': '',
                                          'from_type': 'diary',
                                          'page': "1"},
             '/api/question/create_answer': {'content': '[{"type":"0","content":"测试回复信息安全"}]'},
             '/api/question/create_question': {'city': 'beijing',
                                               'content': '[{"type":"0","content":"大家好，我是来挣美分的"}]',
                                               'in_white_list': '0',
                                               'is_invite_doctor': '1',
                                               'question_type': '0',
                                               'title': '更美软件真好'},
             '/api/question/index': {'refresh_count': '0',
                                     'platform': 'xcx'},
             '/api/report/info': {'doctor_id': '',
                                  'hospital_id': ''},
             '/api/report/upload': {'content': '更美软件更美软件更美软件更美软件',
                                    'doctor_id': '',
                                    'hospital_id': 'bjylzxmryy'},
             '/api/reservation/create': {'order_id': '7994660722',
                                         'time_frame_id': '429646',
                                         'type': '0'},
             '/api/reservation/list': {'type': '0',
                                       'order_id': '7994660722'},
             '/api/sensitivity/check': {'content': '我是来赚取美分的，大家给我点吧',
                                        'filter_type': '1',
                                        'isfilternum': '1'},
             '/api/service/comment/create': {'order_id': '2471339004',
                                             'operation_effect_rating': '5',
                                             'doctor_attitude_rating': '5',
                                             'hospital_env_rating': '5',
                                             'images': '[]',
                                             'comment_option': '[日记本中注释说明]',
                                             'rating': '5'},
             '/api/service/detail/v1': {'coupon_info_id': '',
                                        'is_gray': '1',
                                        'referrer': 'my_cart'},
             '/api/services/v1': {'area_id': '',
                                  'count': '10',
                                  'doctor_id': '',
                                  'hospital_id': '',
                                  'max_price': '',
                                  'min_price': '',
                                  'more_filters': '',
                                  'offset': '',
                                  'order_by': '0',
                                  'tag_id': '',
                                  'tag_ids': ''
                                  }

             }
